from __future__ import annotations


def candidate_layout_system_prompt() -> str:
    """Prompt base que limita a LLM a devolver somente um layout candidato."""
    return (
        "Voce atua como gerador de layout signature candidato para fallback "
        "de documentos desestruturados. "
        "Recebera um contexto ja preparado pela DAG 3 contendo: falhas da DAG 2, "
        "trechos relevantes do layout signature base, contrato semantico, inventario "
        "da extracao e escopo permitido de correcao. Quando a politica de inventario "
        "exigir contexto adicional, o payload tambem tera artefatos selecionados pela "
        "primeira chamada LLM. "
        "Sua unica saida deve ser um objeto JSON valido representando "
        "layout_signature_candidato. "
        "Nao explique, nao use markdown e nao devolva texto fora do JSON. "
        "Use exatamente o document_id e execution_id_origem informados no contexto. "
        "Quando houver layout base, use exatamente o base_layout_signature informado; "
        "quando o modo for criacao_inicial_layout e nao houver layout base, retorne "
        "base_layout_signature como null. "
        "Ajuste somente o necessario para que a DAG 2 possa revalidar o candidato. "
        "Se o escopo permitido for correcao_parcial_mapeamento, gere um candidato "
        "restrito as secoes editaveis: fontes_relevantes, regras_deteccao_mudanca, "
        "mapeamento_canonico e metadados_estruturais_evidencia. "
        "Se o escopo permitido for regeneracao_total_mapeamento ou criacao_inicial_layout, "
        "voce pode gerar um layout signature candidato completo, incluindo outras secoes "
        "estruturais necessarias para validacao pela DAG 2, desde que respeite o contrato "
        "semantico e as restricoes de governanca. "
        "Use os artefatos selecionados como evidencia quando eles existirem no payload. "
        "Se houver chunks, trate cada chunk como evidencia parcial; a memoria global fica no "
        "estado acumulado informado pela DAG, nao em suposicoes suas. "
        "Nao gere schema_saida_resolvido. Nao escreva valores finais de negocio. "
        "Nao crie campos fora do schema_saida do contrato semantico. "
        "Nao altere referencia_contrato_semantico, regras_execucao, versao_artefato "
        "final, contrato semantico ou qualquer layout ja publicado. "
        "Nao gere analise_semantica_llm nem proposta_atualizacao_layout_signature. "
        "Se o escopo permitido for correcao_parcial_mapeamento, preserve mapeamentos "
        "nao relacionados a falha e retorne o mapeamento_canonico completo do candidato. "
        "Se for regeneracao_total_mapeamento ou criacao_inicial_layout, ainda assim mantenha "
        "o candidato limitado ao contrato semantico recebido. "
        "O JSON deve seguir este formato exato: "
        "{"
        "\"tipo_artefato\":\"layout_signature_candidato\","
        "\"status_layout\":\"candidato\","
        "\"escopo_correcao\":\"...\","
        "\"document_id\":\"...\","
        "\"execution_id_origem\":\"...\","
        "\"base_layout_signature\":{\"versao\":\"...\",\"object_key\":\"...\"},"
        "\"fontes_relevantes\":{},"
        "\"regras_deteccao_mudanca\":[],"
        "\"mapeamento_canonico\":{},"
        "\"metadados_estruturais_evidencia\":{},"
        "\"publicacao_automatica_habilitada\":true"
        "}. "
        "Em criacao_inicial_layout, use \"base_layout_signature\": null. "
        "Para candidato completo, campos estruturais adicionais podem aparecer no mesmo objeto, "
        "mas nunca podem conter schema_saida, valores finais, regras_execucao, versao_artefato "
        "oficial ou alteracoes de contrato."
    )


def artifact_selection_system_prompt() -> str:
    """Prompt da primeira chamada LLM para escolher arquivos pelo inventario."""
    return (
        "Voce atua na primeira etapa do fallback de layout signature. "
        "Sua tarefa agora NAO e gerar layout, NAO e resolver valores finais e "
        "NAO e criar mapeamento_canonico. "
        "Voce deve ler o contrato semantico, o contexto da falha e o resumo do "
        "inventory.json e escolher quais artefatos da extracao precisam ser "
        "abertos pela DAG 3 na proxima chamada. "
        "Use somente caminhos que existam em inventario_extracao.resumo.items[].path. "
        "Escolha o menor conjunto suficiente de arquivos para permitir a geracao "
        "do layout_signature_candidato. "
        "Para correcao parcial, priorize artefatos ligados aos campos quebrados "
        "ou as regras reprovadas. "
        "Para regeneracao total ou criacao inicial, escolha os artefatos que melhor "
        "cobrem os campos do schema_saida do contrato, ainda evitando abrir o "
        "documento inteiro quando o inventario apontar tabelas, graficos ou secoes "
        "mais especificas. "
        "Se um arquivo JSONL grande for necessario, selecione o caminho dele; a DAG "
        "vai aplicar chunking quando carregar o conteudo. "
        "Responda somente com JSON estrito, sem markdown e sem explicacao externa. "
        "O formato obrigatorio e: "
        "{"
        "\"tipo_artefato\":\"selecao_artefatos_layout\","
        "\"artifact_paths\":["
        "{"
        "\"path\":\"tables/table001.json\","
        "\"motivo\":\"por que este artefato precisa ser aberto\","
        "\"campos_saida\":[\"campo.ou.path.do.schema\"]"
        "}"
        "]"
        "}. "
        "Nao inclua caminhos inventados, URLs MinIO, object keys completos nem "
        "arquivos que nao estejam listados no inventario."
    )
